#include <QtWidgets>
#include <qglobal.h>
#include <qnetworkaccessmanager.h>
#include <qhostaddress.h>
#include <qnetworkrequest.h>
#include <qnetworkreply.h>
#include <qlineedit.h>
#include <qcryptographichash.h>
#include "SystemVariable.h"